### PR TITLE
Missile cost rebalance

### PR DESCRIPTION
**Pull request by TheDestroyer111**
I am not experienced with modding, but cost values were really weird so I decided to change them in case somebody wants to make a career-mode war DMP server :D 
They are, in general, 1/500 of the real cost values in present-day US dollars. However, many of them have different values for various gameplay reasons. I didn't want a very hardcore approach, so the missiles don't cost more than aircraft, but I think that at least for air-air missiles, the cost should encourage people to use guns whenever missiles are not needed, at least on career war servers ;)
Do you agree with my values, or should I change something?

### CODE REVIEW

**Comment by gomker** [comment]
I haven't researched the math on it but on its face looks good to me.

**Comment by Nerfclasher** [comment]
Yes I think these values are correct but I'm pretty sure that bdac was not developed in mind of career at the time  so I'm not sure and also any  pull requests need to be put on the  support branch

**Comment by Guard13007** [comment]
@Nerfclasher It was not, but (I'm pretty sure) Bahamuto had mentioned rebalancing as a todo for a long time, just not high priority, and people have wanted it for just as long.

**Comment by jrodrigv** [comment]
Merged to master

**Pull request merged**
