### PR TITLE
Ship Launched Weapons Update

### PR DESCRIPTION
**Pull request by gomker**
* Adding new `weaponClass` - SLW - Ship Launched Weapon - intended to target surface vessels (splashed) and submarines (splashed and underwater)

* `weaponClass.SLW` is set by `missileType` `torpedo` or `depthcharge`

* New "Sonar" Implementation - If `RWRThreatTypes` is Sonar will not detect flying vessels, only surface ships and submersibles

* `MAX_ACTIVE_RADAR_RANGE` & `MAX_ENGAGEMENT_RANGE` added to settings.cfg for more control over ranged combat

* Updated checks for Landed and Splashed to be more accurate and account for sumbersibles

* Renamed "Ground" engagement  option to "Surface" to better reflect behavior

* MM Patches updated for engagement options and torpedo types

* Issue Reference #201 for Sonar, RWR Types, engagement Types, torpedo targeting

* Increased Radar Range #170

* Logic for Smart Targeting should correct #216 - Gaurd mode can still get stuck - needs review

### CODE REVIEW

**Comment by zzhwudiaa** [comment]
We (our modding group) Kerwis have a working torpedo/depth charge program, currently used with [NAS](http://forum.kerbalspaceprogram.com/index.php?/topic/118521-wip13-nas-naval-artillery-system-0652-bdac-addon-ww2-naval-weapons-crossroads-20170702/) weapons. It's now unguided only and have an UI which helps with setting depths of all these weapons, hopefully it would help with this project.
https://github.com/Summerfirefly/ASW

Cheers,
Forum user Acea

**Comment by gomker** [comment]
@Acea-K 
Sounds great. To take advantage of the new `engagement` settings all you will need to do to classify a weapon as `SLW` is to set 

`missileType = torpedo` or `missileType = depthcharge`

The same guidance types still apply, working to add a dedicated `SLW` type soon

To change to "Sonar" (effectively the radar that can only detect underwater vessels and surface ships) use

`rwrThreatType = 6`

**Comment by Acea-K** [comment]
@gomker That'd be wonderful.
I have one more question, would torpedoes/depth charges have some kind of aiming mark (like the existing aiming circle) or something similar (or even WoWs-style predicting mark)? Since we're mainly making WWII torpedoes without guidance, aiming could be a problem if only modern torpedoes have been considered.

**Comment by gomker** [comment]
@Acea-K 
We have actually found that the `AAM` guidance works just fine under water. I am using that as a base for the new `SLM` type but that will be phase 2 of this process. Some tweaks are pending for `TerminalGuidance` to better fit underwater combat. As for depth charges I think the bomb aimer circle was going to be the default, but I need to check on that.

This is a sample config by Spanner for a reference torpedo we will be including

     MODULE
    {
	name = MissileLauncher

	shortName = SRayBDA

	thrust = 47.8 //KN thrust during boost phase
	cruiseThrust = 22.2 //thrust during cruise phase
	cruiseDelay = 0   /// delay between boost ending and cruise starting, only used for large ship launched and air drop versions
	dropTime = 8 //how many seconds after release until engine ignites extended drop time allows torpedo to sink to depth, too short a drop time will turn it into a very wayward missile 
	boostTime = 2 //seconds of boost phase
	cruiseTime = 480 //seconds of cruise phase
	//spoolEngine = true // N/A special cases only

	guidanceActive = true //missile has guidanceActive

	decoupleSpeed = 1.5  //f  0.1 steps max value 10
	decoupleForward = true // throws the torpedo out of the tube 
	isTubeLoaded = true
	 
	optimumAirspeed = 45 
	torpedo = true
	waterImpactTolerance = 100

	aero = true
	liftArea = 0.0037
	steerMult = 2
	maxTorque = 45
	maxAoA = 30
	aeroSteerDamping = 5 
	
	missileType = torpedo // used by code to determine characteristics
	homingType = AAM
	targetingType = radar
	activeRadarRange = 8000
	maxOffBoresight = 270
	lockedSensorFOV = 7
	maxTurnRateDPS = 40 //degrees per second

	proxyDetonate = false
	blastRadius = 30 //meters
	blastPower = 30
	blastHeat = 50

	audioClipPath = SM_Marine/Sounds/TorpPropFX
	exhaustPrefabPath = SM_Marine/FX/TorpWake
	boostExhaustPrefabPath = SM_Marine/Parts/WaterJetExperimental/FX/jetdriveWake
	boostTransformName = boostTransform
	boostExhaustTransformName = boostTransform
	radarLOAL = true
	minStaticLaunchRange = 200
	maxStaticLaunchRange = 8000
 }

**Comment by Acea-K** [comment]
@gomker Umm I mean, would the old school fixed-depth cruising torpedo mode be included too?
We've managed to make it work somehow since NAS contents are mainly WW2 weapons, so are the ship based/air launch torpedoes, which would not be guided and only follow a straight path. This way we'll definitely need an aiming method, or the torpedo could go anywhere

**Comment by gomker** [comment]
@Acea-K  
Could be - I just need to figure out how to integrate that into guidance. Really if you guys have it squared in your plugin no reason it could not co-exist with a few tweaks. After we get this first part squared away lets chat in the issue I am using to track the work #201

**Comment by jrodrigv** [comment]
I'm closing this PR. The feature sub branch has been merged into Dev branch now.

**Pull request closed without merging**
