### PR TITLE
Fix to Issue #109

### PR DESCRIPTION
**Pull request by Designer225**
Same as #290 but with changes redone into `dev` branch.

### CODE REVIEW

**Comment by TheDogKSP** [comment]
I believe the code needs some cleanup and refactoring before merging (or re-implementing).

Some questions after reviewing:

1. Why have some raycasts which do terrain checks be amended with altered bit masks?
   Example "CanSeePosition" in BDATargetManager:
   original raycast with bit mask "557057" already includes bits 0, 15, and 19.
   the additional raycast with bit mask "2228224" includes only 17 and 21.

   First, this can be combined into a single raycast with bit mask 0, 15, 17, 19 and 21 (decimal 2785281) for better performance (raycasts are expensive). This applies basically to most spots where the additionla bit masks are checked (dont combine raycasts with ||, instead supply encompassing bit mask).

   Second, for this specific example with canseeposition, while a hit on a kerbal should be detected for weapons impact, I dont quite understand why a kerbal hit is relevant for code like canseeposition, which deals with terrain occlusion (cannot see a vessel behind a mountain, etc). I dont think a kerbal should occlude sth behind it.

2. I dont understand the additional layer check for layer 17: while I do understand layer 21 (part triggers), the KSP API lists layer 17 as "editor UI". Why would that be relevant for kerbal hit detection??

3. Just a note: we are currently reworking the whole damage and bullet penetration system, to avoid conflicts we might not merge this PR soon. Dont worry, we'll come back to this. Still I may do some refactoring instead of merging as-is, as explained above.

**Comment by Designer225** [comment]
@TheDogKSP Thanks for your feedback. I will make changes into the code now.

**Comment by Designer225** [comment]
I had made and tested the changes.

Some things to note:
1. KerbalEVA the Part no longer has a collider associated with it. That has been moved to KerbalEVA the PartModule. While the existing part damage system still works, I did make minor changes to it so that it works properly with Kerbals.

2. Because of the above issue, BDArmor.GetArmor causes NullReferenceException when KerbalEVA the part is passed as a parameter. I made changes to PooledBullet (since that seems to be the only class that uses BDArmor) so that Kerbals are skipped when checking armor.

3. Layer 17 is now EVA, not Editor UI: https://forum.kerbalspaceprogram.com/index.php?/topic/84273-unity-layers-and-tags-updated-09-march-2017/

**Comment by TheDogKSP** [comment]
Oh, wow, thanks! Actually I didnt mean that you have to do those changs, but anyway, thanks!
And also thanks for clearing up the layer 17 thing - I totally missed it had been redefined. So fully makes sense.

As I said, we will definitely merge this, just waiting for news on the armor/damage rewrite now...

**Comment by TheDogKSP** [comment]
testing locally...

**Comment by TheDogKSP** [comment]
merged with latest commit to dev
Thank you very much for your PR, this is great work! Kerbals will be destructible again next release thanks to you!

**Pull request closed without merging**
