### PR TITLE
MM patch for localization and EN-US language file

### PR DESCRIPTION
**Pull request by Acea-K**
Created a MM patch file to unify format of all part description tags, and added full EN-US localization texts (with original text quotes).

### CODE REVIEW

**Comment by gomker** [comment]
@Acea-K we had to merge some items from the Dev branch which caused this to have some conflicts.
Would you mind syncing up your fork and resolving them - if you need any assistance let me know.
Sorry for the switch up , it was merge that needed priority for refactor.

**Comment by TheDogKSP** [comment]
testing locally...

**Comment by Acea-K** [comment]
This file is quite early, and may not contain all latest parts.
I could also provide Chinese localization file if necessary.

**Comment by TheDogKSP** [comment]
Thanks! I am closing this PR, because I just merged it manually.
If you have further chinese localisations for us, we happily take them.
Please check out the branch "dev" and submit your PR against it.

**Pull request closed without merging**
