### PR TITLE
AI Improvements for AA/AG 

### PR DESCRIPTION
**Pull request by TheDogKSP**
(I am still on KSP 1.1.3, so this PR is against master, not support, I am sorry...)

Additional features:
- show right-mouse-button information in editor (VAB/SPH) for guns, missiles and radar

Fixes:
- for air-ground missiles, prevent firing full complement at once (respect maxMissilesTarget)
- prevent gps guided missiles being used on air targets/incoming missiles
- try to improve selection of AA missiles/guns against incoming missiles

### CODE REVIEW

**Comment by Nerfclasher** [comment]
I think you should move this to support branch and could you please join the team

**Comment by TheDogKSP** [comment]
Hi guys,

No problem, I'll port it to the support branch (just need to install the
KSP 1.2 preview myself so I can compile it here).

I am quite interested in BDArmory and I am willing to joi you guys, no
problem, - just cannot make any promises regarding the time I can invest,
due to RL and other stuff.
And I am not a unity expert, I have to say.

But if I can help you out with fixing and/or the rewrite, sure, no worries.

Will try to have the code in the support branch tomorrow.

Cheers,
TheDog

**Comment by TheDogKSP** [comment]
opened a new one on the support branch, should I close this one?

**Comment by Nerfclasher** [comment]
Yes but since I have been removed from the team ask papa joe

**Comment by PapaJoesSoup** [comment]
Hey.  Sorry for the delayed response.  We will take a look.  Thanks for the effort here!  With 1.2 popping soon, we want to be sure we have a stable build before implementing.

**Comment by TheDogKSP** [comment]
Sure, no worries!
As I said, I don't even know if my changes are really a good idea or done
correctly without other side effects, it just improves behaviour of my
aegis frigate.

Should you require some more hands for the upcoming tasks, I'd be happy to
assist, though I cannot commit on how much time I could invest.
I can do general c# programming/debugging/ testing, though I am definitely
not a pro in unity. Just let me know in case.

Cheers,
TheDog

**Comment by Nerfclasher** [comment]
Thanks for answering because I was the one who  pointed to him to you

**Comment by gomker** [comment]
@TheDogKSP  This one can be closed right as you opened another for the Support branch?

**Comment by TheDogKSP** [comment]
closing this one

**Pull request closed without merging**
