### PR TITLE
Duplicated name from 'AGM-114 Hellfire Missile EMP'

### PR DESCRIPTION
**Pull request by alex-dev**
I was parsing my ConfigCache and got a duplicate key exception building a dictionary. Considering I doubt it is intended, I'm proposing a quick fix.
If it is intended, is it possible to disable the .cfg file so the part is not loaded?

### CODE REVIEW

**Comment by alex-dev** [comment]
The same issue is present with:
- the 3 version of the bahaM1Abrams 'M1 Abrams Cannon';

It is not a localized issue. I'm willing to document them all if it is an actual oversight. If it is intended I would like either an explication or a way to avoid duplicated name. It makes parsing the database a pain.

**Comment by Gedas-S** [comment]
@alex-dev thanks for noticing!
I believe some of these are test parts which shouldn't be in the releases altogether :) We should just delete those.

https://github.com/PapaJoesSoup/BDArmory/blob/master/BDArmory/Distribution/GameData/BDArmory/Parts/hellfireMissile/HellfireEMP.cfg
https://github.com/PapaJoesSoup/BDArmory/blob/master/BDArmory/Distribution/GameData/BDArmory/Parts/m1Abrams/m1Abrams_he.cfg
https://github.com/PapaJoesSoup/BDArmory/blob/master/BDArmory/Distribution/GameData/BDArmory/Parts/m1Abrams/m1Abrams_sabot.cfg

**Comment by alex-dev** [comment]
Ok. Well do make sure they are test parts... I'll post a full list of duplicated later today. Just gotta check my parsing logs.

**Comment by Gedas-S** [comment]
There are two Hellfire EMP, one has a proper name and is intended to stay in BDA, the other is a test part.

**Comment by Gedas-S** [comment]
I removed the parts in #632

**Pull request closed without merging**
