### PR TITLE
add a new feature about bullets

### PR DESCRIPTION
**Pull request by Luoluo-MostHandsomeOne**
add a new feature about bullets
Now bullets can penetrate the parts(depending on the thickness of the collider and bullets config)
(need config files)

### CODE REVIEW

**Comment by Luoluo-MostHandsomeOne** [comment]
BULLET
{
    name = bulletname
	positiveCoefficient = 0.2 //from 0 to 1
	penetration   //m,mm
	{
		key = 0 299
		key = 10 295
		key = 100 291
		key = 500 278
		key = 1000 250
		key = 1500 237
		key = 2000 200
	}
}

**Comment by SpannerMonkey** [comment]
Hi this is quite an interesting development do you have a link to a compiled DLL I could test along with your test ammo?
I'm presuming that the first number  of the key is the range of the target from the projectile spawn point and the second is the depth of penetration of a collider.  What is the positiveCoefficient = 0.2 //from 0 to 1 and what effect does it have ?  is it tied to shell mass? 

Cheers
SpannerMonkey (BDAc team member)

**Comment by Luoluo-MostHandsomeOne** [comment]
Thanks for your reply
It can help penetration from an oblique angle to increase the penetration depth of the projectile.
0 means that the shell will not change the angle, and 1 means that the projectile will penetrate the armor at normal incidence.
[BDArmory.zip](https://github.com/PapaJoesSoup/BDArmory/files/433877/BDArmory.zip)

**Comment by jrodrigv** [comment]
@Luoluo-MostHandsomeOne  I have renamed branches to a Feature style so things can be tested in isolation. Can you update your fork and open a new PR to the branch "Feature_BulletPenetration". Thanks!

**Comment by jrodrigv** [comment]
@Luoluo-MostHandsomeOne  No need to create a new PR. I've changed the base to the new branch

**Pull request closed without merging**
